apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: us-east1
  name: llm-router
  namespace: '796982368079'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: 9f070fae-0e59-4208-b78b-c7bd3a01b65b
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - command:
        - llm_router
        image: gcr.io/hoth-410100/github.com/aivillage/llm_router@sha256:cda3a98212410fffa8943282a7ded540daa270d56312e6eefba1747663978bf2
        name: llm-router-1
        ports:
        - containerPort: 8000
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8000
          timeoutSeconds: 240
        volumeMounts:
        - mountPath: /opt/models
          name: models
      serviceAccountName: 796982368079-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
      volumes:
      - csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: llm-router-config
        name: models
  traffic:
  - latestRevision: true
    percent: 100
