apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama2-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama2-7b
  template:
    metadata:
      labels:
        app: llama2-7b
    spec:
      containers:
      - name: llama2-7b
        image: ghcr.io/huggingface/text-generation-inference:1.3.4
        resources:
          limits:
            nvidia.com/gpu: "1"
        env:
        - name: MODEL_ID
          value: meta-llama/Llama-2-7b-chat-hf
        - name: NUM_SHARD
          value: "1"
        - name: PORT
          value: "8080"
        - name: QUANTIZE
          value: bitsandbytes
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: l4-demo
              key: HUGGING_FACE_TOKEN
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
      volumes:
        - name: dshm
          emptyDir:
              medium: Memory
        - name: data
          emptyDir: {}
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-p100
        cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
        cloud.google.com/gke-spot: "true"
