apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistral-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mistral-7b
  template:
    metadata:
      labels:
        app: mistral-7b
    spec:
      containers:
      - name: llm
        image: ghcr.io/huggingface/text-generation-inference:1.3.4
        resources:
          limits:
            nvidia.com/gpu: "1"
        env:
        - name: MODEL_ID
          value: mistralai/Mistral-7B-Instruct-v0.2
        - name: NUM_SHARD
          value: "1"
        - name: PORT
          value: "8080"
        - name: QUANTIZE
          value: bitsandbytes-nf4
        - name: SLIDING_WINDOW
          value: "-1"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
      volumes:
        - name: dshm
          emptyDir:
              medium: Memory
        - name: data
          emptyDir: {}
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-p100
        cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
        cloud.google.com/gke-spot: "true"
