# This is a development image for testing Vault secrets. Do not use in production.

FROM hashicorp/vault:1.14

EXPOSE 8200
ADD vault-init.sh /

RUN chmod 755 vault-init.sh

ENTRYPOINT ["./vault-init.sh"]