name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  contents: read


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tests
      run: |
        touch .env_keys
        cargo generate-lockfile
        make test
